name: Dockerhub_cd

on:
  push:

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Hacer checkout del c√≥digo
      - name: Checkout repository
        uses: actions/checkout@v5
     # Paso 2: Login a dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    # Paso 3: Build and push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
